apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ok1f2xbvy-dotnet-basic
  janus-idp.io/tekton: ok1f2xbvy-dotnet-basic
  backstage.io/kubernetes-id: ok1f2xbvy-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok1f2xbvy-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
